apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::560553425296:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J9NZ19JSWCLD
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::560553425296:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-15T16:06:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1405"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5bcf2612-4403-4464-88a8-a96d8bbe8abb
